// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: membershipmodule/membership/member.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/x/auth/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MembershipStatus enumerates the valid membership states for a citizen of The
// Denom
type MembershipStatus int32

const (
	// MEMBERSHIP_STATUS_UNDEFINED defines a no-op status
	MembershipStatus_MemberStatusEmpty MembershipStatus = 0
	// MEMBERSHIP_STATUS_ELECTORATE defines this member as being an active citizen
	MembershipStatus_MemberElectorate MembershipStatus = 1
	// MEMBERSHIP_STATUS_INACTIVE defines this member as being an inactive citizen
	MembershipStatus_MemberInactive MembershipStatus = 2
	// MEMBERSHIP_STATUS_RECALLED defines this member as being recalled
	MembershipStatus_MemberRecalled MembershipStatus = 3
	// MEMBERSHIP_STATUS_EXPULSED defines this member as being expulsed
	MembershipStatus_MemberExpulsed MembershipStatus = 4
)

var MembershipStatus_name = map[int32]string{
	0: "MEMBERSHIP_STATUS_UNDEFINED",
	1: "MEMBERSHIP_STATUS_ELECTORATE",
	2: "MEMBERSHIP_STATUS_INACTIVE",
	3: "MEMBERSHIP_STATUS_RECALLED",
	4: "MEMBERSHIP_STATUS_EXPULSED",
}

var MembershipStatus_value = map[string]int32{
	"MEMBERSHIP_STATUS_UNDEFINED":  0,
	"MEMBERSHIP_STATUS_ELECTORATE": 1,
	"MEMBERSHIP_STATUS_INACTIVE":   2,
	"MEMBERSHIP_STATUS_RECALLED":   3,
	"MEMBERSHIP_STATUS_EXPULSED":   4,
}

func (x MembershipStatus) String() string {
	return proto.EnumName(MembershipStatus_name, int32(x))
}

func (MembershipStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ba2fc082642cdf4, []int{0}
}

// Member is a specialisation of BaseAccount that adds Member Status and
// Nickname
type Member struct {
	*types.BaseAccount `protobuf:"bytes,1,opt,name=base_account,json=baseAccount,proto3,embedded=base_account" json:"base_account,omitempty"`
	Status             MembershipStatus `protobuf:"varint,2,opt,name=status,proto3,enum=membershipmodule.membership.MembershipStatus" json:"status,omitempty"`
	Nickname           string           `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	IsGuardian         bool             `protobuf:"varint,4,opt,name=is_guardian,json=isGuardian,proto3" json:"is_guardian,omitempty"`
}

func (m *Member) Reset()      { *m = Member{} }
func (*Member) ProtoMessage() {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba2fc082642cdf4, []int{0}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Member.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return m.Size()
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("membershipmodule.membership.MembershipStatus", MembershipStatus_name, MembershipStatus_value)
	proto.RegisterType((*Member)(nil), "membershipmodule.membership.Member")
}

func init() {
	proto.RegisterFile("membershipmodule/membership/member.proto", fileDescriptor_5ba2fc082642cdf4)
}

var fileDescriptor_5ba2fc082642cdf4 = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd2, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0x07, 0xf0, 0x4c, 0xb7, 0x94, 0x3a, 0x95, 0x25, 0x0e, 0x2b, 0x94, 0xac, 0xa4, 0xc1, 0x53,
	0x10, 0x9a, 0xb0, 0x15, 0x16, 0xf4, 0x96, 0xb6, 0xa3, 0x06, 0xda, 0xba, 0x24, 0xa9, 0x88, 0x97,
	0x32, 0x49, 0x87, 0x36, 0x98, 0x64, 0x42, 0x66, 0xb2, 0xec, 0x7e, 0x03, 0xe9, 0xc9, 0xa3, 0x97,
	0xca, 0x7e, 0x1c, 0x8f, 0x3d, 0x7a, 0x12, 0x6d, 0xbf, 0x88, 0x98, 0x84, 0x6d, 0xd9, 0x55, 0x6f,
	0x6f, 0xfe, 0x79, 0xbf, 0x37, 0x81, 0x79, 0x50, 0x8f, 0x69, 0xec, 0xd3, 0x8c, 0x2f, 0xc3, 0x34,
	0x66, 0xf3, 0x3c, 0xa2, 0xe6, 0x3e, 0xa8, 0x4a, 0x23, 0xcd, 0x98, 0x60, 0xe8, 0xf4, 0x6e, 0xa7,
	0xb1, 0x0f, 0x94, 0x93, 0x05, 0x5b, 0xb0, 0xa2, 0xcf, 0xfc, 0x53, 0x95, 0x44, 0x51, 0x03, 0xc6,
	0x63, 0xc6, 0x4d, 0x92, 0x8b, 0xa5, 0x79, 0x79, 0xe6, 0x53, 0x41, 0xce, 0x8a, 0x43, 0xf9, 0xfd,
	0xe9, 0x2f, 0x00, 0x1b, 0xe3, 0x62, 0x08, 0xb2, 0xe1, 0x43, 0x9f, 0x70, 0x3a, 0x23, 0x41, 0xc0,
	0xf2, 0x44, 0xb4, 0x81, 0x06, 0xf4, 0x56, 0x4f, 0x33, 0xca, 0x09, 0x46, 0x81, 0xaa, 0x09, 0x46,
	0x9f, 0x70, 0x6a, 0x95, 0x7d, 0xfd, 0xfa, 0xe6, 0x47, 0x07, 0x38, 0x2d, 0x7f, 0x1f, 0x21, 0x0c,
	0x1b, 0x5c, 0x10, 0x91, 0xf3, 0x76, 0x4d, 0x03, 0xfa, 0x71, 0xaf, 0x6b, 0xfc, 0xe7, 0xcf, 0x8d,
	0xf1, 0x6d, 0xe9, 0x16, 0xc8, 0xa9, 0x30, 0x52, 0x60, 0x33, 0x09, 0x83, 0x8f, 0x09, 0x89, 0x69,
	0xfb, 0x48, 0x03, 0xfa, 0x03, 0xe7, 0xf6, 0x8c, 0x3a, 0xb0, 0x15, 0xf2, 0xd9, 0x22, 0x27, 0xd9,
	0x3c, 0x24, 0x49, 0xbb, 0xae, 0x01, 0xbd, 0xe9, 0xc0, 0x90, 0xbf, 0xae, 0x92, 0x97, 0xcd, 0x4f,
	0x37, 0x1d, 0xe9, 0xcb, 0x4d, 0x47, 0x7a, 0xf6, 0xb5, 0x06, 0xe5, 0xbb, 0x77, 0xa0, 0x73, 0x78,
	0x3a, 0xc6, 0xe3, 0x3e, 0x76, 0xdc, 0x37, 0xf6, 0xc5, 0xcc, 0xf5, 0x2c, 0x6f, 0xea, 0xce, 0xa6,
	0x93, 0x21, 0x7e, 0x65, 0x4f, 0xf0, 0x50, 0x96, 0x94, 0xc7, 0xab, 0xb5, 0xf6, 0xa8, 0x64, 0x25,
	0xc1, 0x71, 0x2a, 0xae, 0xd1, 0x39, 0x7c, 0x72, 0xdf, 0xe1, 0x11, 0x1e, 0x78, 0x6f, 0x1d, 0xcb,
	0xc3, 0x32, 0x50, 0x4e, 0x56, 0x6b, 0xad, 0xba, 0x0f, 0x47, 0x34, 0x10, 0x2c, 0x23, 0x82, 0xa2,
	0x1e, 0x54, 0xee, 0x3b, 0x7b, 0x62, 0x0d, 0x3c, 0xfb, 0x1d, 0x96, 0x6b, 0x0a, 0x5a, 0xad, 0xb5,
	0xe3, 0x52, 0xd9, 0x09, 0x09, 0x44, 0x78, 0xf9, 0x0f, 0xe3, 0xe0, 0x81, 0x35, 0x1a, 0xe1, 0xa1,
	0x7c, 0x74, 0x68, 0x1c, 0x1a, 0x90, 0x28, 0xa2, 0xf3, 0xbf, 0x1b, 0xfc, 0xfe, 0x62, 0x3a, 0x72,
	0xf1, 0x50, 0xae, 0x1f, 0x1a, 0x7c, 0x95, 0xe6, 0x11, 0xa7, 0xf3, 0xbe, 0xfb, 0x6d, 0xab, 0x82,
	0xcd, 0x56, 0x05, 0x3f, 0xb7, 0x2a, 0xf8, 0xbc, 0x53, 0xa5, 0xcd, 0x4e, 0x95, 0xbe, 0xef, 0x54,
	0xe9, 0xc3, 0x8b, 0x45, 0x28, 0x96, 0xb9, 0x6f, 0x04, 0x2c, 0x36, 0x13, 0x96, 0x85, 0xa4, 0x9b,
	0x50, 0x61, 0x96, 0x4f, 0xd8, 0x3d, 0x58, 0xd3, 0xab, 0xc3, 0x9d, 0x15, 0xd7, 0x29, 0xe5, 0x7e,
	0xa3, 0x58, 0xb0, 0xe7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x96, 0xbb, 0xd7, 0xde, 0xdf, 0x02,
	0x00, 0x00,
}

func (m *Member) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Member) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Member) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsGuardian {
		i--
		if m.IsGuardian {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.Nickname) > 0 {
		i -= len(m.Nickname)
		copy(dAtA[i:], m.Nickname)
		i = encodeVarintMember(dAtA, i, uint64(len(m.Nickname)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Status != 0 {
		i = encodeVarintMember(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if m.BaseAccount != nil {
		{
			size, err := m.BaseAccount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMember(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMember(dAtA []byte, offset int, v uint64) int {
	offset -= sovMember(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Member) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BaseAccount != nil {
		l = m.BaseAccount.Size()
		n += 1 + l + sovMember(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovMember(uint64(m.Status))
	}
	l = len(m.Nickname)
	if l > 0 {
		n += 1 + l + sovMember(uint64(l))
	}
	if m.IsGuardian {
		n += 2
	}
	return n
}

func sovMember(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMember(x uint64) (n int) {
	return sovMember(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Member) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Member: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Member: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseAccount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BaseAccount == nil {
				m.BaseAccount = &types.BaseAccount{}
			}
			if err := m.BaseAccount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= MembershipStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nickname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nickname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsGuardian", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsGuardian = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMember(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMember
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMember
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMember
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMember
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMember
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMember
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMember        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMember          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMember = fmt.Errorf("proto: unexpected end of group")
)
